{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOdpVBOKmRNAcLO4v7UFrcX"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"vThRZgsxkT09","executionInfo":{"status":"ok","timestamp":1681925526226,"user_tz":-330,"elapsed":20,"user":{"displayName":"unabdriged","userId":"17458716221866330189"}},"outputId":"fe69c5ab-e52c-41c3-9ea5-3877148fe593"},"outputs":[{"output_type":"stream","name":"stdout","text":["hello\n"]}],"source":["print(\"hello\")\n"]},{"cell_type":"code","source":["%tensorflow_version 2.x\n","import tensorflow as tf\n","print(tf.version)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"n-H-flZUViVN","executionInfo":{"status":"ok","timestamp":1681971975830,"user_tz":-330,"elapsed":5128,"user":{"displayName":"unabdriged","userId":"17458716221866330189"}},"outputId":"d344491b-e1fa-4bd2-c0dd-17957bf82a05"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.\n","<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/version/__init__.py'>\n"]}]},{"cell_type":"code","metadata":{"id":"p4xpuxwKHOGL","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1682097116728,"user_tz":-330,"elapsed":1918,"user":{"displayName":"unabdriged","userId":"17458716221866330189"}},"outputId":"f1d5f918-5167-4681-98f5-36e7abbd2a76"},"source":["!pip install -q sklearn"],"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n","\n","\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n","\u001b[1;36mhint\u001b[0m: See above for details.\n"]}]},{"cell_type":"code","source":["%tensorflow_version 2.x "],"metadata":{"id":"fKjyOR-VzXLq","executionInfo":{"status":"ok","timestamp":1682097144201,"user_tz":-330,"elapsed":489,"user":{"displayName":"unabdriged","userId":"17458716221866330189"}},"outputId":"2392a198-604d-4f45-9d37-f3396f9c93c4","colab":{"base_uri":"https://localhost:8080/"}},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.\n"]}]}]}